---
- name:
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: Start Apache
      service:
        name: apache2
        state: started
    -name: enable Apache
      service:
        name: apache2
        enabled: yes    